/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule PostUpvoter.graphql
 * @generated SignedSource<<098ddc2762c4d8f6ec279571b6132b58>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type PostUpvoter = {|
  +id: string;
  +votes: number;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "PostUpvoter",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "votes",
      "storageKey": null
    }
  ],
  "type": "Post"
};

module.exports = fragment;
