/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule SubmitQuery.graphql
 * @generated SignedSource<<e95367827211c9a18ccd3e2e7c111c0f>>
 * @relayHash 873ec0574786327dea0e9757864c6123
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/


/*
query SubmitQuery {
  viewer {
    ...Submit
    id
  }
}

fragment Submit on Viewer {
  id
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "SubmitQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": "viewer",
        "args": null,
        "concreteType": "Viewer",
        "name": "__viewer_viewer",
        "plural": false,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "Submit",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "SubmitQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "SubmitQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Viewer",
        "name": "viewer",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          }
        ],
        "storageKey": null
      },
      {
        "kind": "LinkedHandle",
        "alias": null,
        "args": null,
        "handle": "viewer",
        "name": "viewer",
        "key": "",
        "filters": null
      }
    ]
  },
  "text": "query SubmitQuery {\n  viewer {\n    ...Submit\n    id\n  }\n}\n\nfragment Submit on Viewer {\n  id\n}\n"
};

module.exports = batch;
